apiVersion: apps/v1
kind: Deployment
metadata:
  name: crealo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crealo
  template:
    metadata:
      labels:
        app: crealo
    spec:
      containers:
        - name: crealo
          image: 893194976256.dkr.ecr.us-east-2.amazonaws.com/docker-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: crealo
    k8s-app: crealo
  name: crealo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: crealo